### ISSUE TITLE
Link to this repo from user manual

### ISSUE THREAD

**Issue by mhuebert** [shadow-cljs/shadow-cljs.github.io#2]
(for ease of viewing source / submitting an issue or PR)

**Comment by mhuebert** [comment]
The link to source is now a couple of pages in the middle of the doc and not easy to find. I'd like to add a [source] link in the header, right after `Thomas Heller and Tony Kay Version 1.0, Jan 10, 2018`. I couldn't figure out how to do this by looking at the source.

**Comment by thheller** [comment]
Hmm is the "Contributing" link in the left TOC not enough?

I'm not sure its possible to add something in the top section?

**Comment by mhuebert** [comment]
I think I’ve grown to expect to see a link to github at the top (or, in the case of an “edit this page” link, perhaps the bottom) of whatever I’m looking at. It took me a few minutes to find this repo, as it didn’t show up in my google searching and I didn’t expect to find it in the middle. Obviously I didn’t read the table of contents carefully tho.
