### ISSUE TITLE
What do you think about translations?

### ISSUE THREAD

**Issue by lksilva** [shadow-cljs/shadow-cljs.github.io#48]
Hi, I started to learn about clojure a few months ago and I wish so much to contribute to shadow-cljs documentation in order to improve my english and learn about shadow-cljs, I'm in love with that tools. So, I would like to know if there is a way to contribute translating this documentation for pt-BR?

**Comment by thheller** [comment]
That would be fantastic but unfortunately I don't think there is an easy way to do this. Best way might be to fork this repo and just publishing it separately? Would be happy to add links to the proper places.

**Comment by lksilva** [comment]
I will do some researches if there is as way to do that with [asciidoctor](https://asciidoctor.org/) or a similar way that enable us complete, if not I can start a fork =)
