### ISSUE TITLE
3.2.1 Leiningen

### ISSUE THREAD

**Issue by numinasthmatic** [shadow-cljs/shadow-cljs.github.io#5]
_…there is a simple option in your shadow-cljs.edn file that causes it to derive :source-paths and :dependencies from project.clj:_
This option does not seem to be explained.
I'm making minor suggested corrections to the book at the moment. I'll make a PR when I have a few collected.

**Comment by thheller** [comment]
That might not be worded perfectly but the example for it is in the next example below?

**Comment by numinasthmatic** [comment]
Is this right?

If you'd like to use Leiningen for your build system (particularly if you use Cursive), the `shadow-cljs` command-line utility can be configured to use `lein` to run your commands. Enable this by adding a `:lein` entry to your `shadow-cljs.edn` config. With `:lein` set the `shadow-cljs` command will use `lein` to launch the JVM, and `:source-paths` and `:dependencies` will be derived from `project.clj`.

**Comment by thheller** [comment]
>  and :source-paths and :dependencies will be derived from project.clj.

Is not entirely correct since it doesn't derive anything. It just runs things through `lein` so neither `:source-paths` or `:dependencies` from `shadow-cljs.edn` will have any effect. I guess its close enough though.

**Comment by numinasthmatic** [comment]
If you'd like to use Leiningen for your build system (particularly if you use Cursive), the `shadow-cljs` command-line utility can be configured to use `lein` to run your commands. Enable this by adding a `:lein` entry to your `shadow-cljs.edn` config. With this setting, the `shadow-cljs` command will use `lein` to launch the JVM, ignoring any `:source-paths` and `:dependencies` in `shadow-cljs.edn`; relying instead on `lein` to set them from `project.clj`.
